spring:
  application:
       name: devcoin
  data:
    mongodb:
      host: localhost
      port: 27017
      database: devcoin
      username: root
      password: root
      authentication-database: admin

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

    circuitbreaker:
      resilience4j:
        enabled: true